-- CREATE DATABASE armony;
USE armony;

DROP TABLE IF EXISTS cita;
DROP TABLE IF EXISTS detalleVenta;
DROP TABLE IF EXISTS venta;
DROP TABLE IF EXISTS inventario;
DROP TABLE IF EXISTS valoracion;
DROP TABLE IF EXISTS favoritos;
DROP TABLE IF EXISTS servEmp;
DROP TABLE IF EXISTS promociones;
DROP TABLE IF EXISTS prodServ;
DROP TABLE IF EXISTS sucursal;
DROP TABLE IF EXISTS empleado;
DROP TABLE IF EXISTS patologias;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS membresia;
DROP TABLE IF EXISTS tipoPilar;

-- AGREGAR CAMPOS DE DATOS DE PATOLOGIAS

-- DEFINIR COMO ASIGNAR FOTOS

-- DEFINIR COMO ASIGNAR ID


CREATE TABLE tipoPilar (
	pkIdPilar INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(15) NOT NULL,
    PRIMARY KEY (pkIdPilar)
) ENGINE InnoDB;

CREATE TABLE membresia (
	pkIdMembresia INT UNSIGNED NOT NULL,
    nombre VARCHAR(25) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    -- rango TINYINT NOT NULL, -- DEFINIR BIEN RANGOS
    duracion TIME NOT NULL,
    costo DECIMAL(7,2) NOT NULL,
    PRIMARY KEY (pkIdMembresia)
) ENGINE InnoDB;

CREATE TABLE categoria (
	pkIdCategoria INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fkPilar INT UNSIGNED NOT NULL,
    nombre VARCHAR(15) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    PRIMARY KEY (pkIdCategoria),
    CONSTRAINT FKPilar1 FOREIGN KEY (fkPilar) REFERENCES tipoPilar (pkIdPilar)
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE usuario (
	pkIdUsuario INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(75) NOT NULL,
    telefono VARCHAR(10) NOT NULL,
    pass VARCHAR(64) NOT NULL,
    tipo TINYINT NOT NULL,
    -- token VARCHAR(256) DEFAULT NULL,
    -- estado BOOLEAN,
	-- foto
    PRIMARY KEY (pkIdUsuario)
) ENGINE InnoDB;

CREATE TABLE cliente (
	fkUsuario INT UNSIGNED NOT NULL, -- DEFINIR COMO ASIGNAR ID
    fkMembresia INT UNSIGNED DEFAULT NULL,
    nombre VARCHAR(25) NOT NULL,
    apellidoP VARCHAR(20) NOT NULL,
    apellidoM VARCHAR(20) NOT NULL,
    duracionMem TIME DEFAULT NULL,
    PRIMARY KEY (fkUsuario),
    CONSTRAINT FKUser1 FOREIGN KEY (fkUsuario) REFERENCES usuario (pkIdUsuario) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKMem2 FOREIGN KEY (fkMembresia) REFERENCES membresia (pkIdMembresia) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE InnoDB;

CREATE TABLE patologias (
	fkCliente INT UNSIGNED NOT NULL,
    -- AGREGAR CAMPOS DE DATOS DE PATOLOGIAS
    PRIMARY KEY (fkCliente),
    CONSTRAINT FKCliente1 FOREIGN KEY (fkCliente) REFERENCES cliente (fkUsuario) 
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;

CREATE TABLE empleado (
	fkUsuario INT UNSIGNED NOT NULL, -- DEFINIR COMO ASIGNAR ID
    nombre VARCHAR(25) NOT NULL,
    apellidoP VARCHAR(20) NOT NULL,
    apellidoM VARCHAR(20) NOT NULL,
    horaEntrada TIME NOT NULL,
    horaSalida TIME NOT NULL,
	valoracion DECIMAL(2,1) NOT NULL,
    activo BOOLEAN,
    PRIMARY KEY (fkUsuario),
    CONSTRAINT FKUser2 FOREIGN KEY (fkUsuario) REFERENCES usuario (pkIdUsuario) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE sucursal (
	pkIdSucursal INT UNSIGNED NOT NULL AUTO_INCREMENT,
	calle VARCHAR(30) NOT NULL,
	colonia VARCHAR(30) NOT NULL,
	numero VARCHAR(4) NOT NULL,
	codigoPostal VARCHAR(5) NOT NULL,
	horaApertura TIME NOT NULL,
	horaCierre TIME NOT NULL,
	valoracion DECIMAL(2,1) NOT NULL,
    PRIMARY KEY (pkIdSucursal)
) ENGINE InnoDB;

CREATE TABLE prodServ (
	pkIdPS INT UNSIGNED NOT NULL AUTO_INCREMENT,
	fkCat INT UNSIGNED NOT NULL,
	nombre VARCHAR(25) NOT NULL,
	precio DECIMAL(7,2) NOT NULL,
	descripcion VARCHAR(100) NOT NULL,
	estado BOOLEAN,
	valoracion DECIMAL(2,1) NOT NULL,
	-- imagen
	tiempo TIME DEFAULT NULL,
	PRIMARY KEY (pkIdPS),
    CONSTRAINT FKCat1 FOREIGN KEY (fkCat) REFERENCES categoria (pkIdCategoria) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE promociones (
	pkIdPromocion INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fkMembresia INT UNSIGNED NOT NULL,
    fkPS INT UNSIGNED NOT NULL, -- TAL VEZ RELACIONAR CON TABLA CAT
    descripcion VARCHAR(100) NOT NULL,
    valorDescuento DECIMAL(7,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (pkIdPromocion),
    CONSTRAINT FKMem1 FOREIGN KEY (fkMembresia) REFERENCES membresia (pkIdMembresia) 
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FKPS1 FOREIGN KEY (fkPS) REFERENCES prodServ (pkIdPS) 
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;

CREATE TABLE servEmp (
	fkEmpleado INT UNSIGNED NOT NULL,
    fkServ INT UNSIGNED NOT NULL,
    PRIMARY KEY (fkEmpleado, fkServ),
    CONSTRAINT FKEmp1 FOREIGN KEY (fkEmpleado) REFERENCES empleado (fkUsuario)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FKServ1 FOREIGN KEY (fkServ) REFERENCES prodServ (pkIdPS)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;

CREATE TABLE favoritos (
	fkCliente INT UNSIGNED NOT NULL,
    fkProd INT UNSIGNED NOT NULL,
    PRIMARY KEY (fkCliente, fkProd),
    CONSTRAINT FKCliente2 FOREIGN KEY (fkCliente) REFERENCES cliente (fkUsuario)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FKProd1 FOREIGN KEY (fkProd) REFERENCES prodServ (pkIdPS)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;

CREATE TABLE valoracion (
-- LA RELACIÓN DE LO QUE SE VALORA SOLO DEBE IR UN SOLO PRODUCTO, SUCURSAL O EMPLEADO, NO PUEDE HABER 2 O MÁS.
	pkIdValoracion INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fkCliente INT UNSIGNED NOT NULL,
    fkPS INT UNSIGNED DEFAULT NULL,
    fkSucursal INT UNSIGNED DEFAULT NULL,
    fkEmpleado INT UNSIGNED DEFAULT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    comentario VARCHAR(100),
    valoracion DECIMAL(2,1),
    PRIMARY KEY (pkIdValoracion),
    CONSTRAINT FKCliente3 FOREIGN KEY (fkCliente) REFERENCES cliente (fkUsuario) 
		ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FKPS2 FOREIGN KEY (fkPS) REFERENCES prodServ (pkIdPS) 
		ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FKSucursal1 FOREIGN KEY (fkSucursal) REFERENCES sucursal (pkIdSucursal) 
		ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FKEmp2 FOREIGN KEY (fkEmpleado) REFERENCES empleado (fkUsuario) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE inventario (
	fkSucursal INT UNSIGNED NOT NULL,
	fkPS INT UNSIGNED NOT NULL,
	stock INT UNSIGNED NOT NULL,
	PRIMARY KEY (fkSucursal, fkPS),
    CONSTRAINT FKSucursal2 FOREIGN KEY (fkSucursal) REFERENCES sucursal (pkIdSucursal) 
		ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FKPS3 FOREIGN KEY (fkPS) REFERENCES prodServ (pkIdPS) 
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;

CREATE TABLE venta (
	pkIdVenta INT UNSIGNED NOT NULL AUTO_INCREMENT,
	fkCliente INT UNSIGNED NOT NULL,
	total DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
	serieComprobante VARCHAR(18) NOT NULL,
	impuesto DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
	fecha DATE NOT NULL,
	estado BOOLEAN,
	PRIMARY KEY (pkIdVenta),
    CONSTRAINT FKCliente4 FOREIGN KEY (fkCliente) REFERENCES cliente (fkUsuario) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE detalleVenta (
	fkPS INT UNSIGNED NOT NULL,
	fkVenta INT UNSIGNED NOT NULL,
	fkPromocion INT UNSIGNED DEFAULT NULL,
	cantidad INT UNSIGNED NOT NULL,
	precio DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (fkPS, fkVenta),
    CONSTRAINT FKPS4 FOREIGN KEY (fkPS) REFERENCES prodServ (pkIdPS) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKMem3 FOREIGN KEY (fkPS) REFERENCES membresia (pkIdMembresia) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKVenta1 FOREIGN KEY (fkVenta) REFERENCES venta (pkIdVenta) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKPromo1 FOREIGN KEY (fkPromocion) REFERENCES promociones (pkIdPromocion) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;

CREATE TABLE cita (
	fkVenta INT UNSIGNED NOT NULL,
	fkEmpleado INT UNSIGNED NOT NULL,
	fkSucursal INT UNSIGNED NOT NULL,
	fecha DATE NOT NULL,
	horaIn TIME NOT NULL,
	horaFin TIME NOT NULL,
	Descripcion VARCHAR(100) NOT NULL,
	PRIMARY KEY (fkVenta),
    CONSTRAINT FKVenta2 FOREIGN KEY (fkVenta) REFERENCES venta (pkIdVenta) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKEmp3 FOREIGN KEY (fkEmpleado) REFERENCES empleado (fkUsuario) 
		ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FKSucursal3 FOREIGN KEY (fkSucursal) REFERENCES sucursal (pkIdSucursal) 
		ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE InnoDB;
